-- Run once on an existing V8.x D1 database.
ALTER TABLE users ADD COLUMN email_verified INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN blocked INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN token_limit INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,name TEXT NOT NULL,icon TEXT NOT NULL DEFAULT '🚀',instructions TEXT NOT NULL DEFAULT '',memory TEXT NOT NULL DEFAULT '',chat_ids_json TEXT NOT NULL DEFAULT '[]',file_ids_json TEXT NOT NULL DEFAULT '[]',archived INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id,updated_at DESC);
CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL,schedule TEXT NOT NULL,next_run INTEGER NOT NULL,prompt TEXT NOT NULL,delivery TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,last_run INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_tasks_due ON tasks(enabled,next_run);
CREATE TABLE IF NOT EXISTS task_runs(id TEXT PRIMARY KEY,task_id TEXT NOT NULL,user_id TEXT,result TEXT,status TEXT,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS password_reset_tokens(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS email_verification_tokens(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS login_events(id TEXT PRIMARY KEY,user_id TEXT,ip TEXT,country TEXT,device TEXT,success INTEGER NOT NULL,reason TEXT,suspicious INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS abuse_reports(id TEXT PRIMARY KEY,user_id TEXT,chat_id TEXT,reason TEXT NOT NULL,content TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created_at INTEGER NOT NULL,resolved_at INTEGER);
CREATE TABLE IF NOT EXISTS moderation_queue(id TEXT PRIMARY KEY,user_id TEXT,content TEXT,verdict TEXT,status TEXT NOT NULL DEFAULT 'open',created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS error_logs(id TEXT PRIMARY KEY,user_id TEXT,route TEXT,message TEXT,stack TEXT,ip TEXT,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS admin_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at INTEGER NOT NULL);
