import Constants from 'expo-constants';import NetInfo from '@react-native-community/netinfo';import {tokenStore} from '@/services/auth/tokenStore';import {enqueue,pendingQueue,removeQueued,bumpQueued} from '@/services/storage/offlineDb';import type {ApiErrorShape} from '@/types';import {resolveApiUrl} from '@/constants/config';
// The base URL is validated by resolveApiUrl(): production requires public HTTPS and
// rejects localhost/127.0.0.1/10.0.2.2/private LAN hosts. There is no silent fallback.
const base=resolveApiUrl((Constants.expoConfig?.extra?.apiUrl as string|undefined)??process.env.EXPO_PUBLIC_API_URL);let refreshPromise:Promise<boolean>|undefined;
export class ApiError extends Error{constructor(public status:number,public payload:ApiErrorShape){super(payload.message);this.name='ApiError'}}
export type Options={signal?:AbortSignal;timeoutMs?:number;queueOffline?:boolean;idempotencyKey?:string};
function rid(){return `${Date.now()}-${Math.random().toString(36).slice(2)}`}
async function refresh(){if(refreshPromise)return refreshPromise;refreshPromise=(async()=>{const token=await tokenStore.getRefresh();if(!token)return false;try{const r=await fetch(`${base}/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:token})});if(!r.ok)return false;const t=await r.json();await tokenStore.set(t.access_token,t.refresh_token);return true}catch{return false}finally{refreshPromise=undefined}})();return refreshPromise}
async function raw<T>(path:string,init:RequestInit={},o:Options={},retry=true):Promise<T>{const c=new AbortController();const timer=setTimeout(()=>c.abort(),o.timeoutMs??30000);const abort=()=>c.abort();o.signal?.addEventListener('abort',abort,{once:true});try{const headers=new Headers(init.headers);if(!(init.body instanceof FormData))headers.set('Content-Type','application/json');const token=await tokenStore.getAccess();if(token)headers.set('Authorization',`Bearer ${token}`);headers.set('X-Client','mobile');headers.set('X-Request-ID',rid());if(o.idempotencyKey)headers.set('Idempotency-Key',o.idempotencyKey);const r=await fetch(base+path,{...init,headers,signal:c.signal});if(r.status===401&&retry&&await refresh())return raw(path,init,o,false);if(r.status===401)await tokenStore.clear();if(!r.ok){let p:ApiErrorShape={code:`HTTP_${r.status}`,message:'Request failed'};try{const body=await r.json() as {error?:ApiErrorShape}&ApiErrorShape;p=body.error??body}catch{}throw new ApiError(r.status,p)}if(r.status===204)return undefined as T;return await r.json() as T}finally{clearTimeout(timer);o.signal?.removeEventListener('abort',abort)}}
async function mutate<T>(method:string,path:string,body:unknown,o:Options={}){if((await NetInfo.fetch()).isConnected===false&&o.queueOffline){await enqueue(method,path,body);return {queued:true} as T}return raw<T>(path,{method,body:body===undefined?undefined:JSON.stringify(body)},o)}
export const api={get:<T>(p:string,o:Options={})=>raw<T>(p,{},o),post:<T>(p:string,b?:unknown,q:boolean|Options=false)=>mutate<T>('POST',p,b,typeof q==='boolean'?{queueOffline:q}:q),put:<T>(p:string,b:unknown,o:Options={})=>mutate<T>('PUT',p,b,o),patch:<T>(p:string,b:unknown,o:Options={})=>mutate<T>('PATCH',p,b,o),delete:<T>(p:string,o:Options={})=>raw<T>(p,{method:'DELETE'},o),upload:<T>(p:string,f:FormData,o:Options={})=>raw<T>(p,{method:'POST',body:f},{...o,timeoutMs:o.timeoutMs??180000})};
export async function flushOfflineQueue(){for(const x of await pendingQueue()){try{await raw(x.path,{method:x.method,body:x.body??undefined},{idempotencyKey:`offline-${x.id}`,timeoutMs:60000});await removeQueued(x.id)}catch{await bumpQueued(x.id)}}}
