import { Pressable,RefreshControl,StyleSheet,View } from 'react-native'; import { router } from 'expo-router'; import { Ionicons } from '@expo/vector-icons'; import { Screen } from '@/components/ui/Screen'; import { Text } from '@/components/ui/Text'; import { Card } from '@/components/ui/Card'; import { Button } from '@/components/ui/Button'; import { Progress } from '@/components/ui/Progress'; import { StatCard } from '@/components/cards/StatCard'; import { useDashboard } from '@/features/dashboard/useDashboard'; import { useAuth } from '@/features/auth/AuthProvider'; import { useTheme } from '@/theme/useTheme';
export default function Dashboard(){const {user}=useAuth();const c=useTheme();const q=useDashboard();const d=q.data;return <Screen><View style={s.header}><View><Text muted>Good to see you</Text><Text variant="display">{user?.displayName?.split(' ')[0]??'Learner'}</Text></View><Pressable accessibilityLabel="Quick create" onPress={()=>router.push('/create-modal')} style={[s.quick,{backgroundColor:c.primary}]}><Ionicons name="add" size={26} color="#fff"/></Pressable></View>
{q.isError&&<Card><Text variant="subtitle">Dashboard unavailable</Text><Text muted>Pull to retry. Saved notes remain available in Library.</Text><Button label="Retry" onPress={()=>q.refetch()}/></Card>}
{d?.continueLearning&&<Card><View style={s.row}><View style={{flex:1,gap:5}}><Text variant="caption" muted>CONTINUE LEARNING</Text><Text variant="subtitle">{d.continueLearning.title}</Text></View><Text style={{color:c.primary,fontWeight:'700'}}>{Math.round(d.continueLearning.progress*100)}%</Text></View><Progress value={d.continueLearning.progress}/><Button label="Resume" onPress={()=>router.push(`/(main)/notes/${d.continueLearning?.id}`)}/></Card>}
<View style={s.wrap}><StatCard label="Study streak" value={`${d?.streak??0} days`} detail="Keep the rhythm"/><StatCard label="Quiz accuracy" value={`${Math.round((d?.quizAccuracy??0)*100)}%`} detail="Last 30 days"/></View>
<Card><View style={s.row}><Text variant="subtitle">Today's revision</Text><Text style={{color:c.primary,fontWeight:'700'}}>{d?.revisionCount??0} cards</Text></View><Text muted>{d?.revisionCount?'Focus on due cards and previous mistakes.':'You are clear for today.'}</Text><Button label="Start revision" variant="secondary" onPress={()=>router.push('/(main)/revision')}/></Card>
{!!d?.weakTopics.length&&<View style={{gap:10}}><Text variant="subtitle">Weak topics</Text>{d.weakTopics.slice(0,3).map(x=><Pressable key={x.topic} onPress={()=>router.push({pathname:'/(main)/studypack',params:{topic:x.topic}})}><Card style={s.row}><Text style={{flex:1}}>{x.topic}</Text><Text style={{color:c.attention,fontWeight:'700'}}>{Math.round(x.score*100)}%</Text></Card></Pressable>)}</View>}
{!!d?.recentNotes.length&&<View style={{gap:10}}><Text variant="subtitle">Recent notes</Text>{d.recentNotes.slice(0,3).map(n=><Pressable key={n.id} onPress={()=>router.push(`/(main)/notes/${n.id}`)}><Card><Text style={{fontWeight:'700'}}>{n.title}</Text><Text variant="caption" muted>{n.topic??'Study note'}</Text></Card></Pressable>)}</View>}
{!!d?.recommendedTopics.length&&<Card><Text variant="subtitle">Recommended next</Text><View style={{gap:8}}>{d.recommendedTopics.slice(0,3).map((x,i)=><Text key={x}>{i+1}. {x}</Text>)}</View></Card>}
{d?.upcomingExam&&<Card style={{backgroundColor:c.primarySoft}}><Text variant="caption" style={{color:c.primary,fontWeight:'700'}}>UPCOMING EXAM</Text><Text variant="subtitle">{d.upcomingExam.name}</Text><Text>{new Date(d.upcomingExam.date).toLocaleDateString()}</Text></Card>}</Screen>}
const s=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingTop:8},quick:{width:52,height:52,borderRadius:18,alignItems:'center',justifyContent:'center'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:12},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12}});
