import { QRDesignConfig } from '../../types/qr';

export const QR_PRESET_STYLES: QRDesignConfig[] = [
  {
    presetName: 'ZOSUF Neon',
    fgColor: '#8b5cf6',
    bgColor: '#0c0e24',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#06b6d4',
    gradientRotation: 45,
    dotType: 'extra-rounded',
    cornerSquareType: 'extra-rounded',
    cornerDotType: 'dot',
    cornerSquareColor: '#a855f7',
    cornerDotColor: '#22d3ee',
    errorCorrection: 'Q',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
    frameLabel: 'SCAN ME',
    frameStyle: 'bottom-bar',
    frameColor: '#7c3aed',
    frameTextColor: '#ffffff',
  },
  {
    presetName: 'Midnight Violet',
    fgColor: '#c084fc',
    bgColor: '#0f0728',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#e879f9',
    gradientRotation: 90,
    dotType: 'classy-rounded',
    cornerSquareType: 'rounded',
    cornerDotType: 'rounded',
    cornerSquareColor: '#d8b4fe',
    cornerDotColor: '#f472b6',
    errorCorrection: 'M',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
  },
  {
    presetName: 'Cyber Grid',
    fgColor: '#06b6d4',
    bgColor: '#02121e',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#10b981',
    gradientRotation: 135,
    dotType: 'square',
    cornerSquareType: 'square',
    cornerDotType: 'square',
    cornerSquareColor: '#22d3ee',
    cornerDotColor: '#34d399',
    errorCorrection: 'M',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
    frameLabel: 'OPEN ME',
    frameStyle: 'neon-border',
    frameColor: '#06b6d4',
  },
  {
    presetName: 'Aurora Gradient',
    fgColor: '#3b82f6',
    bgColor: '#050b14',
    transparentBg: false,
    gradientType: 'radial',
    gradientColor2: '#ec4899',
    gradientRotation: 0,
    dotType: 'dots',
    cornerSquareType: 'extra-rounded',
    cornerDotType: 'dot',
    cornerSquareColor: '#60a5fa',
    cornerDotColor: '#f43f5e',
    errorCorrection: 'Q',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
  },
  {
    presetName: 'Retro Pixel',
    fgColor: '#10b981',
    bgColor: '#090a0f',
    transparentBg: false,
    gradientType: 'none',
    gradientColor2: '#10b981',
    gradientRotation: 0,
    dotType: 'square',
    cornerSquareType: 'square',
    cornerDotType: 'square',
    cornerSquareColor: '#10b981',
    cornerDotColor: '#10b981',
    errorCorrection: 'M',
    margin: 20,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
  },
  {
    presetName: 'Comic Pop',
    fgColor: '#000000',
    bgColor: '#fef08a',
    transparentBg: false,
    gradientType: 'none',
    gradientColor2: '#000000',
    gradientRotation: 0,
    dotType: 'rounded',
    cornerSquareType: 'rounded',
    cornerDotType: 'dot',
    cornerSquareColor: '#000000',
    cornerDotColor: '#dc2626',
    errorCorrection: 'Q',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
    frameLabel: 'FOR YOU',
    frameStyle: 'card',
    frameColor: '#000000',
    frameTextColor: '#ffffff',
  },
  {
    presetName: 'Glass Glow',
    fgColor: '#a78bfa',
    bgColor: '#181829',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#67e8f9',
    gradientRotation: 60,
    dotType: 'dots',
    cornerSquareType: 'dot',
    cornerDotType: 'dot',
    cornerSquareColor: '#c4b5fd',
    cornerDotColor: '#a5f3fc',
    errorCorrection: 'H',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
  },
  {
    presetName: 'Minimal Mono',
    fgColor: '#09090b',
    bgColor: '#ffffff',
    transparentBg: false,
    gradientType: 'none',
    gradientColor2: '#09090b',
    gradientRotation: 0,
    dotType: 'square',
    cornerSquareType: 'square',
    cornerDotType: 'square',
    cornerSquareColor: '#09090b',
    cornerDotColor: '#09090b',
    errorCorrection: 'M',
    margin: 20,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
    frameLabel: 'SCAN ME',
    frameStyle: 'bottom-bar',
    frameColor: '#09090b',
    frameTextColor: '#ffffff',
  },
  {
    presetName: 'Soft Pastel',
    fgColor: '#6366f1',
    bgColor: '#f8fafc',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#ec4899',
    gradientRotation: 45,
    dotType: 'rounded',
    cornerSquareType: 'rounded',
    cornerDotType: 'rounded',
    cornerSquareColor: '#4f46e5',
    cornerDotColor: '#db2777',
    errorCorrection: 'M',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
  },
  {
    presetName: 'Festival Colors',
    fgColor: '#d946ef',
    bgColor: '#0f172a',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#f59e0b',
    gradientRotation: 90,
    dotType: 'dots',
    cornerSquareType: 'rounded',
    cornerDotType: 'dot',
    cornerSquareColor: '#e879f9',
    cornerDotColor: '#fbbf24',
    errorCorrection: 'Q',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
  },
  {
    presetName: 'Birthday Party',
    fgColor: '#ec4899',
    bgColor: '#2a081a',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#fbbf24',
    gradientRotation: 45,
    dotType: 'classy',
    cornerSquareType: 'extra-rounded',
    cornerDotType: 'dot',
    cornerSquareColor: '#f472b6',
    cornerDotColor: '#fde047',
    errorCorrection: 'Q',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
    frameLabel: 'BIRTHDAY SURPRISE',
    frameStyle: 'bottom-bar',
    frameColor: '#db2777',
    frameTextColor: '#ffffff',
  },
  {
    presetName: 'Friendship Theme',
    fgColor: '#f43f5e',
    bgColor: '#1c0a14',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#fb923c',
    gradientRotation: 30,
    dotType: 'rounded',
    cornerSquareType: 'rounded',
    cornerDotType: 'rounded',
    cornerSquareColor: '#fb7185',
    cornerDotColor: '#fdba74',
    errorCorrection: 'M',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
    frameLabel: 'FRIENDSHIP CHALLENGE',
    frameStyle: 'bottom-bar',
    frameColor: '#e11d48',
    frameTextColor: '#ffffff',
  },
  {
    presetName: 'Love Note',
    fgColor: '#e11d48',
    bgColor: '#ffffff',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#f43f5e',
    gradientRotation: 60,
    dotType: 'classy-rounded',
    cornerSquareType: 'extra-rounded',
    cornerDotType: 'dot',
    cornerSquareColor: '#be123c',
    cornerDotColor: '#fb7185',
    errorCorrection: 'Q',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
    frameLabel: 'SECRET MESSAGE',
    frameStyle: 'bottom-bar',
    frameColor: '#e11d48',
    frameTextColor: '#ffffff',
  },
  {
    presetName: 'Mystery QR',
    fgColor: '#7c3aed',
    bgColor: '#05050d',
    transparentBg: false,
    gradientType: 'radial',
    gradientColor2: '#1e1b4b',
    gradientRotation: 0,
    dotType: 'dots',
    cornerSquareType: 'dot',
    cornerDotType: 'dot',
    cornerSquareColor: '#a78bfa',
    cornerDotColor: '#c4b5fd',
    errorCorrection: 'H',
    margin: 20,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
    frameLabel: 'MYSTERY INSIDE',
    frameStyle: 'bottom-bar',
    frameColor: '#5b21b6',
    frameTextColor: '#ede9fe',
  },
  {
    presetName: 'Prank Mode',
    fgColor: '#84cc16',
    bgColor: '#140c24',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#a855f7',
    gradientRotation: 120,
    dotType: 'extra-rounded',
    cornerSquareType: 'extra-rounded',
    cornerDotType: 'rounded',
    cornerSquareColor: '#a3e635',
    cornerDotColor: '#c084fc',
    errorCorrection: 'Q',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
    frameLabel: 'SURPRISE',
    frameStyle: 'bottom-bar',
    frameColor: '#65a30d',
    frameTextColor: '#ffffff',
  },
  {
    presetName: 'Scan to Reveal',
    fgColor: '#0ea5e9',
    bgColor: '#081320',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#6366f1',
    gradientRotation: 45,
    dotType: 'classy',
    cornerSquareType: 'rounded',
    cornerDotType: 'dot',
    cornerSquareColor: '#38bdf8',
    cornerDotColor: '#818cf8',
    errorCorrection: 'M',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
    frameLabel: 'OPEN ME',
    frameStyle: 'bottom-bar',
    frameColor: '#0284c7',
    frameTextColor: '#ffffff',
  },
  {
    presetName: 'Gaming Style',
    fgColor: '#10b981',
    bgColor: '#0a0a14',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#8b5cf6',
    gradientRotation: 135,
    dotType: 'square',
    cornerSquareType: 'extra-rounded',
    cornerDotType: 'square',
    cornerSquareColor: '#34d399',
    cornerDotColor: '#a78bfa',
    errorCorrection: 'M',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
  },
  {
    presetName: 'Indian Celebration',
    fgColor: '#ea580c',
    bgColor: '#1e0a24',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#ca8a04',
    gradientRotation: 45,
    dotType: 'rounded',
    cornerSquareType: 'rounded',
    cornerDotType: 'dot',
    cornerSquareColor: '#f97316',
    cornerDotColor: '#eab308',
    errorCorrection: 'Q',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
    frameLabel: 'SCAN TO PAY',
    frameStyle: 'bottom-bar',
    frameColor: '#c2410c',
    frameTextColor: '#ffffff',
  },
  {
    presetName: 'Black and Gold',
    fgColor: '#d4af37',
    bgColor: '#09090b',
    transparentBg: false,
    gradientType: 'linear',
    gradientColor2: '#ffd700',
    gradientRotation: 45,
    dotType: 'classy',
    cornerSquareType: 'rounded',
    cornerDotType: 'dot',
    cornerSquareColor: '#e5c158',
    cornerDotColor: '#fff1a8',
    errorCorrection: 'H',
    margin: 20,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
    frameLabel: 'VIEW IMAGE',
    frameStyle: 'neon-border',
    frameColor: '#d4af37',
  },
  {
    presetName: 'Custom Brand',
    fgColor: '#ffffff',
    bgColor: '#111827',
    transparentBg: false,
    gradientType: 'none',
    gradientColor2: '#ffffff',
    gradientRotation: 0,
    dotType: 'rounded',
    cornerSquareType: 'rounded',
    cornerDotType: 'rounded',
    cornerSquareColor: '#ffffff',
    cornerDotColor: '#ffffff',
    errorCorrection: 'M',
    margin: 15,
    size: 512,
    logoSize: 0.2,
    logoMargin: 4,
  },
];
