import React, { useState } from 'react';
import { Download, Copy, Printer, Share2, ShieldCheck, AlertTriangle } from 'lucide-react';
import { StudioDesignState } from '../../../types/qrStudio';

interface Props { currentDesign: StudioDesignState; qrSourceCanvas: HTMLCanvasElement | null; rawSvgString?: string; isVerified: boolean; verificationReport?: { verified?: boolean; contrastRatio:number; warnings?:string[] }; }
type Format='png'|'jpeg'|'webp'|'svg';
const sizes:Record<string,[number,number]>={'512':[512,512],'1000':[1000,1000],'2000':[2000,2000],'3000':[3000,3000],'4096':[4096,4096],'social':[1080,1080],'story':[1080,1920]};

async function render(source:HTMLCanvasElement,width:number,height:number,format:Format,quality:number){
 const c=document.createElement('canvas');c.width=width;c.height=height;const x=c.getContext('2d');if(!x)throw new Error('Canvas is unavailable');
 if(format==='jpeg'){x.fillStyle='#fff';x.fillRect(0,0,width,height)}
 const scale=Math.min(width/source.width,height/source.height),dw=source.width*scale,dh=source.height*scale;x.drawImage(source,(width-dw)/2,(height-dh)/2,dw,dh);
 const mime=format==='jpeg'?'image/jpeg':format==='webp'?'image/webp':'image/png';
 const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Export failed')),mime,quality));return {c,blob};
}

export const ExportTab:React.FC<Props>=({qrSourceCanvas,isVerified,verificationReport})=>{
 const [format,setFormat]=useState<Format>('png');const [size,setSize]=useState('1000');const [quality,setQuality]=useState(.95);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const canExport=Boolean(isVerified&&qrSourceCanvas);
 const dims=sizes[size]||sizes['1000'];
 const download=async()=>{if(!qrSourceCanvas||!canExport)return;setBusy(true);setMessage('');try{const {c,blob}=await render(qrSourceCanvas,dims[0],dims[1],format==='svg'?'png':format,quality);let out=blob,ext=format;if(format==='svg'){const png=c.toDataURL('image/png');out=new Blob([`<svg xmlns="http://www.w3.org/2000/svg" width="${dims[0]}" height="${dims[1]}" viewBox="0 0 ${dims[0]} ${dims[1]}"><image width="100%" height="100%" href="${png}"/></svg>`],{type:'image/svg+xml'});}const u=URL.createObjectURL(out);const a=document.createElement('a');a.href=u;a.download=`zosuf-qr-${dims[0]}x${dims[1]}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setMessage('Download created successfully.');}catch(e){setMessage(e instanceof Error?e.message:'Export failed');}finally{setBusy(false)}};
 const copy=async()=>{if(!qrSourceCanvas||!canExport)return;try{const {blob}=await render(qrSourceCanvas,Math.min(1000,dims[0]),Math.min(1000,dims[1]),'png',1);await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);setMessage('QR image copied.');}catch{setMessage('Image clipboard is not supported here. Use Download instead.')}};
 const share=async()=>{if(!qrSourceCanvas||!canExport)return;try{const {blob}=await render(qrSourceCanvas,1000,1000,'png',1);const file=new File([blob],'zosuf-qr.png',{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:'ZOSUF QR Code',files:[file]});else throw new Error();}catch{setMessage('Sharing is unavailable. Download the image instead.')}};
 const print=async()=>{if(!qrSourceCanvas||!canExport)return;const {c}=await render(qrSourceCanvas,1200,1200,'png',1);const w=window.open('','_blank');if(!w){setMessage('Pop-up blocked. Allow pop-ups to print.');return;}w.document.write(`<title>Print ZOSUF QR</title><style>body{margin:0;display:grid;place-items:center;min-height:100vh}img{max-width:90vw;max-height:90vh}</style><img src="${c.toDataURL()}" onload="print();close()">`);w.document.close();};
 return <div className="space-y-5"><div><h2 className="text-xl font-black text-slate-900">Export QR Code</h2><p className="text-xs text-slate-500 mt-1">The complete verified artwork—frame, text, decorations and logo—is exported.</p></div>
 <div className={`rounded-2xl border p-4 flex gap-3 ${canExport?'bg-emerald-50 border-emerald-200':'bg-amber-50 border-amber-200'}`}>{canExport?<ShieldCheck className="w-5 h-5 text-emerald-600"/>:<AlertTriangle className="w-5 h-5 text-amber-600"/>}<div><b className="text-sm text-slate-900">{canExport?'Great! Current design decoded successfully.':'Download locked until this exact design is verified.'}</b><p className="text-xs text-slate-500">{verificationReport?`Contrast ${verificationReport.contrastRatio.toFixed(1)}:1`:'Verification updates automatically in the preview.'}</p></div></div>
 <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="text-xs font-bold text-slate-600">Format<select value={format} onChange={e=>setFormat(e.target.value as Format)} className="mt-1 w-full rounded-xl border px-3 py-2"><option value="png">PNG</option><option value="svg">SVG (complete embedded artwork)</option><option value="jpeg">JPEG</option><option value="webp">WebP</option></select></label><label className="text-xs font-bold text-slate-600">Size<select value={size} onChange={e=>setSize(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"><option value="512">512×512 px</option><option value="1000">1000×1000 px</option><option value="2000">2000×2000 px</option><option value="3000">3000×3000 px</option><option value="4096">4096×4096 px</option><option value="social">1080×1080 Social</option><option value="story">1080×1920 Story</option></select></label></div>
 {(format==='jpeg'||format==='webp')&&<label className="text-xs font-bold text-slate-600">Quality {Math.round(quality*100)}%<input type="range" min="0.5" max="1" step="0.05" value={quality} onChange={e=>setQuality(Number(e.target.value))} className="w-full accent-fuchsia-600"/></label>}
 <button disabled={!canExport||busy} onClick={download} className="w-full py-4 rounded-xl bg-gradient-to-r from-violet-700 to-fuchsia-600 text-white font-black flex items-center justify-center gap-2 shadow-lg disabled:opacity-40"><Download className="w-5 h-5"/>{busy?'Rendering…':'Download QR CODE'}</button>
 <div className="grid grid-cols-3 gap-2"><button disabled={!canExport} onClick={copy} className="rounded-xl border border-slate-200 px-2 py-2 text-xs font-bold flex items-center justify-center gap-1 disabled:opacity-40"><Copy className="w-4 h-4"/>Copy</button><button disabled={!canExport} onClick={share} className="rounded-xl border border-slate-200 px-2 py-2 text-xs font-bold flex items-center justify-center gap-1 disabled:opacity-40"><Share2 className="w-4 h-4"/>Share</button><button disabled={!canExport} onClick={print} className="rounded-xl border border-slate-200 px-2 py-2 text-xs font-bold flex items-center justify-center gap-1 disabled:opacity-40"><Printer className="w-4 h-4"/>Print</button></div>
 {message&&<p className="text-xs text-center text-violet-700 font-semibold">{message}</p>}
 </div>;
};
