from alembic import op
from database.migrations.helpers import create,drop
revision='0004_research';down_revision='0003_embeddings';branch_labels=None;depends_on=None
R=revision
TABLES=[('research_runs', "CREATE TABLE IF NOT EXISTS research_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),owner_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,query text NOT NULL,report text,status varchar(32) NOT NULL DEFAULT 'queued',source_map jsonb NOT NULL DEFAULT '{}',search_count integer NOT NULL DEFAULT 0,fetched_url_count integer NOT NULL DEFAULT 0,fetched_bytes bigint NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())"), ('research_sources', "CREATE TABLE IF NOT EXISTS research_sources(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),research_run_id uuid NOT NULL REFERENCES research_runs(id) ON DELETE CASCADE,source_id uuid NOT NULL REFERENCES sources(id) ON DELETE CASCADE,url text NOT NULL,canonical_url text NOT NULL,title text NOT NULL,domain varchar(255) NOT NULL,publisher varchar(255),author varchar(255),published_at timestamptz,updated_at timestamptz,retrieved_at timestamptz NOT NULL DEFAULT now(),snippet text NOT NULL,extracted_content text NOT NULL,source_type varchar(40) NOT NULL,provider varchar(50) NOT NULL DEFAULT 'web',quality_score double precision NOT NULL,evidence_score double precision NOT NULL,content_hash varchar(64) NOT NULL,independence_cluster varchar(255),UNIQUE(research_run_id,canonical_url))"), ('claims', 'CREATE TABLE IF NOT EXISTS claims(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),research_run_id uuid NOT NULL REFERENCES research_runs(id) ON DELETE CASCADE,text text NOT NULL,normalized_text text NOT NULL,topic_key varchar(180) NOT NULL,stance varchar(20) NOT NULL,confidence double precision NOT NULL,evidence_status varchar(32) NOT NULL)'), ('evidence', 'CREATE TABLE IF NOT EXISTS evidence(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),claim_id uuid NOT NULL REFERENCES claims(id) ON DELETE CASCADE,research_source_id uuid NOT NULL REFERENCES research_sources(id) ON DELETE CASCADE,quote text NOT NULL,support_score double precision NOT NULL,relation varchar(32) NOT NULL)'), ('citations', "CREATE TABLE IF NOT EXISTS citations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),claim_id uuid NOT NULL REFERENCES claims(id) ON DELETE CASCADE,evidence_id uuid NOT NULL REFERENCES evidence(id) ON DELETE CASCADE,research_source_id uuid NOT NULL REFERENCES research_sources(id) ON DELETE CASCADE,marker varchar(20) NOT NULL,verified boolean NOT NULL DEFAULT false,verification_score double precision NOT NULL,entailment varchar(32) NOT NULL DEFAULT 'unsupported')"), ('research_conflicts', 'CREATE TABLE IF NOT EXISTS research_conflicts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),research_run_id uuid NOT NULL REFERENCES research_runs(id) ON DELETE CASCADE,claim_a text NOT NULL,claim_b text NOT NULL,reason text NOT NULL,confidence double precision NOT NULL)')]
def upgrade():
 op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto');op.execute('CREATE EXTENSION IF NOT EXISTS vector')
 for name,ddl in TABLES:create(R,name,ddl)
def downgrade():
 for name,_ in reversed(TABLES):drop(R,name)
