from alembic import op
from database.migrations.helpers import create,drop
revision='0006_security';down_revision='0005_learning';branch_labels=None;depends_on=None
R=revision
TABLES=[('refresh_tokens', 'CREATE TABLE IF NOT EXISTS refresh_tokens(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash varchar(64) NOT NULL UNIQUE,expires_at timestamptz NOT NULL,revoked_at timestamptz)'), ('account_security', 'CREATE TABLE IF NOT EXISTS account_security(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,email_verified_at timestamptz,failed_login_count integer NOT NULL DEFAULT 0,last_failed_login_at timestamptz,locked_until timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())'), ('device_sessions', 'CREATE TABLE IF NOT EXISTS device_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,device_name varchar(180) NOT NULL,last_seen_at timestamptz NOT NULL DEFAULT now(),revoked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())'), ('session_tokens', 'CREATE TABLE IF NOT EXISTS session_tokens(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),session_id uuid NOT NULL REFERENCES device_sessions(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,family_id uuid NOT NULL,token_hash varchar(64) NOT NULL UNIQUE,expires_at timestamptz NOT NULL,rotated_at timestamptz,revoked_at timestamptz,replaced_by_hash varchar(64))'), ('one_time_tokens', 'CREATE TABLE IF NOT EXISTS one_time_tokens(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,purpose varchar(32) NOT NULL,token_hash varchar(64) NOT NULL UNIQUE,expires_at timestamptz NOT NULL,used_at timestamptz,created_at timestamptz NOT NULL DEFAULT now())'), ('audit_events', "CREATE TABLE IF NOT EXISTS audit_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),actor_id uuid REFERENCES users(id) ON DELETE SET NULL,action varchar(80) NOT NULL,resource_type varchar(50) NOT NULL,resource_id varchar(100),metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now())")]
def upgrade():
 op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto');op.execute('CREATE EXTENSION IF NOT EXISTS vector')
 for name,ddl in TABLES:create(R,name,ddl)
def downgrade():
 for name,_ in reversed(TABLES):drop(R,name)
