from alembic import op
from database.migrations.helpers import create,drop
revision='0010_ai_usage';down_revision='0009_analytics';branch_labels=None;depends_on=None
R=revision
TABLES=[('ai_usage', "CREATE TABLE IF NOT EXISTS ai_usage(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,provider varchar(50) NOT NULL,model varchar(120) NOT NULL,task varchar(50) NOT NULL,feature varchar(50) NOT NULL,request_id varchar(100) NOT NULL UNIQUE,input_tokens integer NOT NULL DEFAULT 0,output_tokens integer NOT NULL DEFAULT 0,total_tokens integer NOT NULL DEFAULT 0,reserved_tokens integer NOT NULL DEFAULT 0,estimated_cost double precision NOT NULL DEFAULT 0,latency_ms integer NOT NULL DEFAULT 0,status varchar(24) NOT NULL,error_type varchar(80),usage_source varchar(20) NOT NULL DEFAULT 'provider',created_at timestamptz NOT NULL DEFAULT now())"), ('plan_definitions', "CREATE TABLE IF NOT EXISTS plan_definitions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code varchar(32) NOT NULL UNIQUE,name varchar(80) NOT NULL,limits jsonb NOT NULL DEFAULT '{}',active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())"), ('subscriptions', 'CREATE TABLE IF NOT EXISTS subscriptions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),owner_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,plan_code varchar(32) NOT NULL,provider varchar(32) NOT NULL,status varchar(24) NOT NULL,provider_subscription_id varchar(120) UNIQUE,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())'), ('entitlements', 'CREATE TABLE IF NOT EXISTS entitlements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),owner_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,key varchar(80) NOT NULL,value jsonb NOT NULL,source varchar(40) NOT NULL,expires_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(owner_id,key))')]
def upgrade():
 op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto');op.execute('CREATE EXTENSION IF NOT EXISTS vector')
 for name,ddl in TABLES:create(R,name,ddl)
 for sql in ["ALTER TABLE account_security ADD COLUMN IF NOT EXISTS last_failed_login_at timestamptz","ALTER TABLE ai_usage ADD COLUMN IF NOT EXISTS task varchar(50) NOT NULL DEFAULT 'legacy'","ALTER TABLE ai_usage ADD COLUMN IF NOT EXISTS total_tokens integer NOT NULL DEFAULT 0","ALTER TABLE ai_usage ADD COLUMN IF NOT EXISTS reserved_tokens integer NOT NULL DEFAULT 0","ALTER TABLE ai_usage ADD COLUMN IF NOT EXISTS latency_ms integer NOT NULL DEFAULT 0","ALTER TABLE ai_usage ADD COLUMN IF NOT EXISTS status varchar(24) NOT NULL DEFAULT 'completed'","ALTER TABLE ai_usage ADD COLUMN IF NOT EXISTS error_type varchar(80)","ALTER TABLE ai_usage ADD COLUMN IF NOT EXISTS usage_source varchar(20) NOT NULL DEFAULT 'estimated'"]:op.execute(sql)
def downgrade():
 for name,_ in reversed(TABLES):drop(R,name)
