from __future__ import annotations
import uuid
from datetime import date,datetime,timezone
from typing import Any
from pgvector.sqlalchemy import Vector
from sqlalchemy import BigInteger,Boolean,Date,DateTime,Float,ForeignKey,Index,Integer,JSON,Sequence,String,Text,UniqueConstraint,text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.database.base import Base

def now()->datetime:return datetime.now(timezone.utc)
class IdMixin:
 id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4)
class TimeMixin:
 created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False)
 updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now,nullable=False)
class User(IdMixin,TimeMixin,Base):
 __tablename__='users'; email:Mapped[str]=mapped_column(String(320),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); display_name:Mapped[str]=mapped_column(String(120)); is_active:Mapped[bool]=mapped_column(Boolean,default=True); is_admin:Mapped[bool]=mapped_column(Boolean,default=False)
 profile:Mapped[Profile|None]=relationship(back_populates='user',cascade='all, delete-orphan',uselist=False)
class Profile(IdMixin,TimeMixin,Base):
 __tablename__='profiles'; user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),unique=True,index=True); subjects:Mapped[list[str]]=mapped_column(JSON,default=list); learning_goal:Mapped[str|None]=mapped_column(String(255)); daily_minutes:Mapped[int]=mapped_column(Integer,default=60); preferences:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict); user:Mapped[User]=relationship(back_populates='profile')
class RefreshToken(IdMixin,Base):
 __tablename__='refresh_tokens'; user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); token_hash:Mapped[str]=mapped_column(String(64),unique=True,index=True); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Subject(IdMixin,TimeMixin,Base):
 __tablename__='subjects'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(180)); course:Mapped[str|None]=mapped_column(String(180)); __table_args__=(UniqueConstraint('owner_id','name',name='uq_subject_owner_name'),)
class Topic(IdMixin,TimeMixin,Base):
 __tablename__='topics'; subject_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('subjects.id',ondelete='CASCADE'),index=True); parent_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('topics.id',ondelete='SET NULL')); name:Mapped[str]=mapped_column(String(220)); syllabus_position:Mapped[int|None]=mapped_column(Integer)
class Note(IdMixin,TimeMixin,Base):
 __tablename__='notes'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); title:Mapped[str]=mapped_column(String(240)); content:Mapped[str]=mapped_column(Text); subject:Mapped[str|None]=mapped_column(String(180),index=True); topic:Mapped[str|None]=mapped_column(String(220),index=True); source_package_id:Mapped[str|None]=mapped_column(String(100)); is_archived:Mapped[bool]=mapped_column(Boolean,default=False,index=True); version:Mapped[int]=mapped_column(Integer,default=1)
 __table_args__=(Index('ix_notes_search',text("to_tsvector('english', coalesce(title,'') || ' ' || coalesce(content,''))"),postgresql_using='gin'),)
class Document(IdMixin,TimeMixin,Base):
 __tablename__='documents'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(255)); mime_type:Mapped[str]=mapped_column(String(160)); size_bytes:Mapped[int]=mapped_column(Integer); storage_key:Mapped[str]=mapped_column(String(500),unique=True); sha256:Mapped[str]=mapped_column(String(64),index=True); status:Mapped[str]=mapped_column(String(32),default='queued',index=True); page_count:Mapped[int|None]=mapped_column(Integer); error_code:Mapped[str|None]=mapped_column(String(80));attempt:Mapped[int]=mapped_column(Integer,default=0);max_attempts:Mapped[int]=mapped_column(Integer,default=3);last_error:Mapped[str|None]=mapped_column(Text);started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));retry_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),index=True)
class Source(IdMixin,TimeMixin,Base):
 __tablename__='sources'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); document_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('documents.id',ondelete='CASCADE'),index=True); kind:Mapped[str]=mapped_column(String(40),index=True); title:Mapped[str]=mapped_column(String(255)); uri:Mapped[str|None]=mapped_column(Text); content_hash:Mapped[str]=mapped_column(String(64)); metadata_json:Mapped[dict[str,Any]]=mapped_column('metadata',JSON,default=dict);expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),index=True)
class ResearchRun(IdMixin,TimeMixin,Base):
 __tablename__='research_runs'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); query:Mapped[str]=mapped_column(Text); report:Mapped[str|None]=mapped_column(Text); status:Mapped[str]=mapped_column(String(32),default='queued'); source_map:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict);search_count:Mapped[int]=mapped_column(Integer,default=0);fetched_url_count:Mapped[int]=mapped_column(Integer,default=0);fetched_bytes:Mapped[int]=mapped_column(BigInteger,default=0)
class StudyArtifact(IdMixin,TimeMixin,Base):
 __tablename__='study_artifacts'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); kind:Mapped[str]=mapped_column(String(40),index=True); topic:Mapped[str]=mapped_column(String(220),index=True); title:Mapped[str]=mapped_column(String(255)); content:Mapped[dict[str,Any]]=mapped_column(JSON); evidence:Mapped[list[dict[str,Any]]]=mapped_column(JSON,default=list); confidence:Mapped[float|None]=mapped_column(Float)
class Question(IdMixin,TimeMixin,Base):
 __tablename__='questions'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); topic:Mapped[str]=mapped_column(String(220),index=True); type:Mapped[str]=mapped_column(String(40)); prompt:Mapped[str]=mapped_column(Text); options:Mapped[list[str]|None]=mapped_column(JSON); answer:Mapped[str]=mapped_column(Text); explanation:Mapped[str]=mapped_column(Text); difficulty:Mapped[str]=mapped_column(String(16),index=True); source_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('sources.id',ondelete='SET NULL'))
class PreviousYearQuestion(IdMixin,TimeMixin,Base):
 __tablename__='previous_year_questions'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); exam:Mapped[str]=mapped_column(String(180),index=True); year:Mapped[int]=mapped_column(Integer,index=True); topic:Mapped[str]=mapped_column(String(220),index=True); prompt:Mapped[str]=mapped_column(Text); marks:Mapped[float|None]=mapped_column(Float); source_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('sources.id',ondelete='RESTRICT'))
class Exam(IdMixin,TimeMixin,Base):
 __tablename__='exams'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(200)); exam_date:Mapped[date]=mapped_column(Date,index=True); syllabus:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict); total_marks:Mapped[int|None]=mapped_column(Integer)
class QuizAttempt(IdMixin,TimeMixin,Base):
 __tablename__='quiz_attempts'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); topic:Mapped[str]=mapped_column(String(220),index=True); score:Mapped[int]=mapped_column(Integer); total:Mapped[int]=mapped_column(Integer); duration_seconds:Mapped[int|None]=mapped_column(Integer); answers:Mapped[list[dict[str,Any]]]=mapped_column(JSON,default=list)
class Flashcard(IdMixin,TimeMixin,Base):
 __tablename__='flashcards'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); topic:Mapped[str]=mapped_column(String(220),index=True); front:Mapped[str]=mapped_column(Text); back:Mapped[str]=mapped_column(Text); due_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True); interval_days:Mapped[int]=mapped_column(Integer,default=0); ease:Mapped[float]=mapped_column(Float,default=2.5); repetitions:Mapped[int]=mapped_column(Integer,default=0); bookmarked:Mapped[bool]=mapped_column(Boolean,default=False)
class FlashcardReview(IdMixin,Base):
 __tablename__='flashcard_reviews'; flashcard_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('flashcards.id',ondelete='CASCADE'),index=True); owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); quality:Mapped[int]=mapped_column(Integer); reviewed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); previous_interval:Mapped[int]=mapped_column(Integer); next_interval:Mapped[int]=mapped_column(Integer)
class StudyPlan(IdMixin,TimeMixin,Base):
 __tablename__='study_plans'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(220)); exam_date:Mapped[date]=mapped_column(Date); daily_minutes:Mapped[int]=mapped_column(Integer); strategy:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict)
class StudyTask(IdMixin,TimeMixin,Base):
 __tablename__='study_tasks'; plan_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('study_plans.id',ondelete='CASCADE'),index=True); owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); title:Mapped[str]=mapped_column(String(255)); scheduled_for:Mapped[date]=mapped_column(Date,index=True); minutes:Mapped[int]=mapped_column(Integer); kind:Mapped[str]=mapped_column(String(40)); status:Mapped[str]=mapped_column(String(32),default='planned',index=True);version:Mapped[int]=mapped_column(Integer,default=1);postponed_from:Mapped[date|None]=mapped_column(Date); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Progress(IdMixin,TimeMixin,Base):
 __tablename__='progress'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); topic:Mapped[str]=mapped_column(String(220),index=True); mastery:Mapped[float]=mapped_column(Float,default=0); confidence:Mapped[float]=mapped_column(Float,default=0);attempt_count:Mapped[int]=mapped_column(Integer,default=0);correct_count:Mapped[int]=mapped_column(Integer,default=0);mistake_count:Mapped[int]=mapped_column(Integer,default=0);study_minutes:Mapped[int]=mapped_column(Integer,default=0); last_reviewed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); next_review_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),index=True); mistakes:Mapped[list[dict[str,Any]]]=mapped_column(JSON,default=list)
 __table_args__=(UniqueConstraint('owner_id','topic',name='uq_progress_owner_topic'),)
class AnalyticsEvent(IdMixin,Base):
 __tablename__='analytics_events'; owner_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),index=True); name:Mapped[str]=mapped_column(String(80),index=True); occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True); properties:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict); session_hash:Mapped[str|None]=mapped_column(String(64))
class CollaborationPermission(IdMixin,TimeMixin,Base):
 __tablename__='collaboration_permissions'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); note_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('notes.id',ondelete='CASCADE'),index=True); grantee_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); role:Mapped[str]=mapped_column(String(16)); share_token_hash:Mapped[str|None]=mapped_column(String(64),unique=True);revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));consumed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Comment(IdMixin,TimeMixin,Base):
 __tablename__='comments'; note_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('notes.id',ondelete='CASCADE'),index=True); author_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); body:Mapped[str]=mapped_column(Text);is_deleted:Mapped[bool]=mapped_column(Boolean,default=False); anchor:Mapped[dict[str,Any]|None]=mapped_column(JSON)
class Embedding(IdMixin,Base):
 __tablename__='embeddings'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); source_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('sources.id',ondelete='CASCADE'),index=True); chunk_index:Mapped[int]=mapped_column(Integer); content:Mapped[str]=mapped_column(Text); token_count:Mapped[int]=mapped_column(Integer); metadata_json:Mapped[dict[str,Any]]=mapped_column('metadata',JSON,default=dict);provider:Mapped[str]=mapped_column(String(50),default='unknown');model:Mapped[str]=mapped_column(String(120),default='unknown');dimension:Mapped[int]=mapped_column(Integer,default=1536);version:Mapped[str]=mapped_column(String(40),default='1'); embedding:Mapped[list[float]]=mapped_column(Vector(1536)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
 __table_args__=(UniqueConstraint('source_id','chunk_index',name='uq_embedding_source_chunk'),Index('ix_embeddings_vector_hnsw','embedding',postgresql_using='hnsw',postgresql_ops={'embedding':'vector_cosine_ops'}),)
class BackgroundTask(IdMixin,TimeMixin,Base):
 __tablename__='background_tasks'; owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); kind:Mapped[str]=mapped_column(String(40),index=True); status:Mapped[str]=mapped_column(String(32),default='queued',index=True); progress:Mapped[float]=mapped_column(Float,default=0); result:Mapped[dict[str,Any]|None]=mapped_column(JSON); error_code:Mapped[str|None]=mapped_column(String(80)); celery_id:Mapped[str|None]=mapped_column(String(80),index=True);attempt:Mapped[int]=mapped_column(Integer,default=0);max_attempts:Mapped[int]=mapped_column(Integer,default=3);last_error:Mapped[str|None]=mapped_column(Text);started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));retry_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class AccountSecurity(IdMixin,TimeMixin,Base):
 __tablename__='account_security';user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),unique=True,index=True);email_verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));failed_login_count:Mapped[int]=mapped_column(Integer,default=0);last_failed_login_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));locked_until:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class DeviceSession(IdMixin,TimeMixin,Base):
 __tablename__='device_sessions';user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True);device_name:Mapped[str]=mapped_column(String(180),default='Mobile device');last_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True);revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),index=True)
class SessionToken(IdMixin,Base):
 __tablename__='session_tokens';session_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('device_sessions.id',ondelete='CASCADE'),index=True);user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True);family_id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),index=True);token_hash:Mapped[str]=mapped_column(String(64),unique=True,index=True);expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True);rotated_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));replaced_by_hash:Mapped[str|None]=mapped_column(String(64))
class OneTimeToken(IdMixin,Base):
 __tablename__='one_time_tokens';user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True);purpose:Mapped[str]=mapped_column(String(32),index=True);token_hash:Mapped[str]=mapped_column(String(64),unique=True,index=True);expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True);used_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class UserIdentity(IdMixin,TimeMixin,Base):
 __tablename__='user_identities';user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True);provider:Mapped[str]=mapped_column(String(32),index=True);subject:Mapped[str]=mapped_column(String(255),index=True);email:Mapped[str|None]=mapped_column(String(320));email_verified:Mapped[bool]=mapped_column(Boolean,default=False);last_login_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
 __table_args__=(UniqueConstraint('provider','subject',name='uq_user_identity_provider_subject'),UniqueConstraint('user_id','provider',name='uq_user_identity_user_provider'))
class AIUsage(IdMixin,Base):
 __tablename__='ai_usage';user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True);provider:Mapped[str]=mapped_column(String(50),index=True);model:Mapped[str]=mapped_column(String(100));task:Mapped[str]=mapped_column(String(50),default='unknown',index=True);feature:Mapped[str]=mapped_column(String(50),index=True);input_tokens:Mapped[int]=mapped_column(Integer);output_tokens:Mapped[int]=mapped_column(Integer);total_tokens:Mapped[int]=mapped_column(Integer,default=0);reserved_tokens:Mapped[int]=mapped_column(Integer,default=0);estimated_cost:Mapped[float]=mapped_column(Float,default=0);latency_ms:Mapped[int]=mapped_column(Integer,default=0);status:Mapped[str]=mapped_column(String(24),default='completed',index=True);error_type:Mapped[str|None]=mapped_column(String(80));usage_source:Mapped[str]=mapped_column(String(20),default='estimated');request_id:Mapped[str]=mapped_column(String(100),unique=True,index=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True)
class ResearchSource(IdMixin,Base):
 __tablename__='research_sources';research_run_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('research_runs.id',ondelete='CASCADE'),index=True);source_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('sources.id',ondelete='CASCADE'),index=True);url:Mapped[str]=mapped_column(Text);canonical_url:Mapped[str]=mapped_column(Text,default='');title:Mapped[str]=mapped_column(Text);domain:Mapped[str]=mapped_column(String(255),index=True);publisher:Mapped[str|None]=mapped_column(String(255));author:Mapped[str|None]=mapped_column(String(255));published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));updated_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));retrieved_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);snippet:Mapped[str]=mapped_column(Text);extracted_content:Mapped[str]=mapped_column(Text);source_type:Mapped[str]=mapped_column(String(40));provider:Mapped[str]=mapped_column(String(50),default='web');independence_cluster:Mapped[str|None]=mapped_column(String(255));quality_score:Mapped[float]=mapped_column(Float,index=True);evidence_score:Mapped[float]=mapped_column(Float);content_hash:Mapped[str]=mapped_column(String(64),index=True)
class Claim(IdMixin,Base):
 __tablename__='claims';research_run_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('research_runs.id',ondelete='CASCADE'),index=True);text:Mapped[str]=mapped_column(Text);normalized_text:Mapped[str]=mapped_column(Text,default='');topic_key:Mapped[str]=mapped_column(String(180),index=True);stance:Mapped[str]=mapped_column(String(20));confidence:Mapped[float]=mapped_column(Float);evidence_status:Mapped[str]=mapped_column(String(32),index=True)
class Evidence(IdMixin,Base):
 __tablename__='evidence';claim_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('claims.id',ondelete='CASCADE'),index=True);research_source_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('research_sources.id',ondelete='CASCADE'),index=True);quote:Mapped[str]=mapped_column(Text);support_score:Mapped[float]=mapped_column(Float);relation:Mapped[str]=mapped_column(String(20))
class Citation(IdMixin,Base):
 __tablename__='citations';claim_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('claims.id',ondelete='CASCADE'),index=True);evidence_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('evidence.id',ondelete='CASCADE'),index=True);research_source_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('research_sources.id',ondelete='CASCADE'),index=True);marker:Mapped[str]=mapped_column(String(20));verified:Mapped[bool]=mapped_column(Boolean,default=False,index=True);verification_score:Mapped[float]=mapped_column(Float);entailment:Mapped[str]=mapped_column(String(32),default='unsupported')
class ResearchConflict(IdMixin,Base):
 __tablename__='research_conflicts';research_run_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('research_runs.id',ondelete='CASCADE'),index=True);claim_a:Mapped[str]=mapped_column(Text);claim_b:Mapped[str]=mapped_column(Text);reason:Mapped[str]=mapped_column(Text);confidence:Mapped[float]=mapped_column(Float)
class TaskControl(IdMixin,Base):
 __tablename__='task_controls';task_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('background_tasks.id',ondelete='CASCADE'),unique=True,index=True);owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True);idempotency_key:Mapped[str]=mapped_column(String(128));cancel_requested:Mapped[bool]=mapped_column(Boolean,default=False);cancel_requested_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));attempts:Mapped[int]=mapped_column(Integer,default=0);__table_args__=(UniqueConstraint('owner_id','idempotency_key',name='uq_task_idempotency'),)
class JobEvent(IdMixin,Base):
 __tablename__='job_events';task_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('background_tasks.id',ondelete='CASCADE'),index=True);sequence:Mapped[int]=mapped_column(Integer);event_type:Mapped[str]=mapped_column(String(40));payload:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True);__table_args__=(UniqueConstraint('task_id','sequence',name='uq_job_sequence'),)
class AuditEvent(IdMixin,Base):
 __tablename__='audit_events';actor_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('users.id',ondelete='SET NULL'),index=True);action:Mapped[str]=mapped_column(String(80),index=True);resource_type:Mapped[str]=mapped_column(String(50));resource_id:Mapped[str|None]=mapped_column(String(100));metadata_json:Mapped[dict[str,Any]]=mapped_column('metadata',JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True)
class KnowledgeEdge(IdMixin,Base):
 __tablename__='knowledge_edges';owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True);from_type:Mapped[str]=mapped_column(String(40));from_id:Mapped[str]=mapped_column(String(100));relation:Mapped[str]=mapped_column(String(40),index=True);to_type:Mapped[str]=mapped_column(String(40));to_id:Mapped[str]=mapped_column(String(100));weight:Mapped[float]=mapped_column(Float,default=1);provenance:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True)

class StudyTaskHistory(IdMixin,Base):
 __tablename__='study_task_history';task_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('study_tasks.id',ondelete='CASCADE'),index=True);owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True);from_status:Mapped[str]=mapped_column(String(32));to_status:Mapped[str]=mapped_column(String(32));from_date:Mapped[date|None]=mapped_column(Date);to_date:Mapped[date|None]=mapped_column(Date);reason:Mapped[str|None]=mapped_column(String(255));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class StudyActivity(IdMixin,Base):
 __tablename__='study_activities';owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True);kind:Mapped[str]=mapped_column(String(40));topic:Mapped[str|None]=mapped_column(String(220));minutes:Mapped[int]=mapped_column(Integer,default=0);score:Mapped[float|None]=mapped_column(Float);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True);metadata_json:Mapped[dict[str,Any]]=mapped_column('metadata',JSON,default=dict)
class NotificationDevice(IdMixin,TimeMixin,Base):
 __tablename__='notification_devices';owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True);token_hash:Mapped[str]=mapped_column(String(64),unique=True);encrypted_token:Mapped[str]=mapped_column(Text);platform:Mapped[str]=mapped_column(String(16));enabled:Mapped[bool]=mapped_column(Boolean,default=True);preferences:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict)
class NotificationEvent(IdMixin,TimeMixin,Base):
 __tablename__='notification_events';owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True);device_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('notification_devices.id',ondelete='SET NULL'));kind:Mapped[str]=mapped_column(String(40));title:Mapped[str]=mapped_column(String(180));body:Mapped[str]=mapped_column(String(500));data:Mapped[dict[str,Any]]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(24),default='queued');attempt:Mapped[int]=mapped_column(Integer,default=0);scheduled_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);delivered_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));last_error:Mapped[str|None]=mapped_column(String(255))
class GeneratedPdf(IdMixin,TimeMixin,Base):
 """Durable metadata for a rendered note PDF (the bytes live in object storage)."""
 __tablename__='generated_pdfs';owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True);note_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('notes.id',ondelete='CASCADE'),index=True);storage_key:Mapped[str]=mapped_column(String(400),unique=True);filename:Mapped[str]=mapped_column(String(255));checksum:Mapped[str]=mapped_column(String(64));byte_size:Mapped[int]=mapped_column(Integer,default=0);renderer_version:Mapped[str]=mapped_column(String(60));status:Mapped[str]=mapped_column(String(24),default='ready');error:Mapped[str|None]=mapped_column(String(500))
